# Generated by Django 5.0.9 on 2024-11-22 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0191_module_bay_rebuild'),
        ('netbox_sdn_controller', '0001_initial'),
        ('tenancy', '0015_contactassignment_rename_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdncontroller',
            old_name='role_regex_template',
            new_name='regex_template',
        ),
        migrations.AddField(
            model_name='sdncontrollerdeviceprototype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenantprototypedevices', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='sdncontroller',
            name='hostname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sdncontrollerdeviceprototype',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='siteprototypedevices', to='dcim.site'),
        ),
        migrations.AlterUniqueTogether(
            name='sdncontroller',
            unique_together={('hostname', 'custom_field_data')},
        ),
    ]
