# Generated by Django 5.0.9 on 2024-11-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_job_object_type_optional'),
        ('dcim', '0191_module_bay_rebuild'),
        ('netbox_sdn_controller', '0002_rename_role_regex_template_sdncontroller_regex_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdncontroller',
            name='last_fetch_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdncontrollerfetch', to='core.job'),
        ),
        migrations.AlterField(
            model_name='sdncontrollerdeviceprototype',
            name='matching_netbox_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchingdevice', to='dcim.device'),
        ),
    ]
