# Generated by Django 5.0.9 on 2024-12-31 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0191_module_bay_rebuild'),
        ('netbox_sdn_controller', '0003_sdncontroller_last_fetch_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetBoxDevice',
            fields=[
            ],
            options={
                'verbose_name': 'netbox device',
                'verbose_name_plural': 'netbox devices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dcim.device',),
        ),
        migrations.AlterModelOptions(
            name='sdncontrollerdeviceprototype',
            options={'ordering': ['instance_uuid', 'stack_index']},
        ),
        migrations.AddField(
            model_name='sdncontrollerdeviceprototype',
            name='stack_index',
            field=models.CharField(default='1'),
        ),
        migrations.AddField(
            model_name='sdncontrollerdeviceprototype',
            name='stack_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='sdncontrollerdeviceprototype',
            name='related_netbox_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relateddevice', to='netbox_sdn_controller.netboxdevice'),
        ),
        migrations.AlterField(
            model_name='sdncontrollerdeviceprototype',
            name='matching_netbox_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchingdevice', to='netbox_sdn_controller.netboxdevice'),
        ),
    ]
