# Generated by Django 5.0.9 on 2025-02-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0191_module_bay_rebuild'),
        ('netbox_sdn_controller', '0004_netboxdevice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SdnDevice',
            fields=[
            ],
            options={
                'verbose_name': 'sdn device',
                'verbose_name_plural': 'sdn devices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dcim.device',),
        ),
        migrations.CreateModel(
            name='SdnModule',
            fields=[
            ],
            options={
                'verbose_name': 'sdn module',
                'verbose_name_plural': 'sdn modules',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dcim.module',),
        ),
    ]
