# Generated by Django 5.0.9 on 2025-04-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_sdn_controller', '0005_sdndevice_sdnmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdncontroller',
            name='last_sync_job_success',
            field=models.BooleanField(default=True),
        ),
    ]
