# Generated by Django 5.0.9 on 2025-04-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_sdn_controller', '0006_sdncontroller_last_sync_job_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdncontrollerdeviceprototype',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
    ]
