# Generated by Django 5.0.9 on 2025-04-09 13:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_sdn_controller', '0007_alter_sdncontrollerdeviceprototype_raw_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sdncontroller',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sdncontroller',
            name='device_families',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterUniqueTogether(
            name='sdncontroller',
            unique_together={('hostname', 'device_families')},
        ),
    ]
