# Generated by Django 5.0.9 on 2025-04-16 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0191_module_bay_rebuild'),
        ('ipam', '0070_vlangroup_vlan_id_ranges'),
        ('netbox_sdn_controller', '0008_alter_sdncontroller_unique_together_and_more'),
        ('tenancy', '0015_contactassignment_rename_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdncontroller',
            name='default_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdncontroller', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='sdncontroller',
            name='sdn_type',
            field=models.CharField(default='Catalyst Center', max_length=30),
        ),
        migrations.AlterField(
            model_name='sdncontrollerdeviceprototype',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prototypeinstances', to='dcim.devicetype'),
        ),
        migrations.AlterField(
            model_name='sdncontrollerdeviceprototype',
            name='primary_ip4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prototype+', to='ipam.ipaddress'),
        ),
        migrations.AlterField(
            model_name='sdncontrollerdeviceprototype',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prototypedevices', to='dcim.devicerole'),
        ),
        migrations.AlterField(
            model_name='sdncontrollerdeviceprototype',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siteprototypedevices', to='dcim.site'),
        ),
        migrations.AlterField(
            model_name='sdncontrollerdeviceprototype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenantprototypedevices', to='tenancy.tenant'),
        ),
    ]
